DSC-ChitkaraUniv/HacktoberFest-2020

- Competitive Coding/Sparsh Garg/trapping_Rain_Water.cpp
Famous Google Interview Problem
> Trapping_Rain_Water.cpp

- Competitive Coding/Ritik/Sum of array.c
> First pull request

- Go/WebServer/Server.go
> feat: implemented a basic golang web server

- Go/Mathematical/Palindrone.go
-  Added code for palindrome checking
> code: added a code for plaindron checking

- Go/Mathematical/binary_search.go
I have implemented a binary search technique in Golang.
Kindly accept my PR. 
Thank You!
> Binary Search Implementation in Golang

- Mobile Development/News_Today.md
"News Today" is an Android App made with Android Studio in Java language.
This app uses freenewsapi to provide up-to-date News in different categories.
Repository link: https://github.com/keshavjain235/News-Today-App
> Added Android App

- Coding/Python/Sorting Dictionaries.py
Considering that dictionaries in Python resembles Maps in Java. A program which sorts a dictionary based on the values and omits out first and second max values in it.
Even sorts the dictionary in desired order.
> Solved Issue #100 Sorting Dictionaries

- Coding/Python/guessnumber.py
> Solved issue #92 guessnumber 

- Coding/C++/binary-search.cpp
- Coding/C/binary-search.c
Added implementation of binary search in C and C++
> Fix: Add binary search to C and C++

- Coding/Java/TicTacToe.java
Added code for a basic game-TicTacToe Under java.
> Added TicTacToe.java

- Coding/Java/StringReverse.java
I edited the previous code as to reverse any string and also trimming extra trailing and in-between spaces present in the strings.
> solving issue 105

- Mobile Development/Weather-App.md
Weather is an Android App made with Android Studio in Java language.
This app uses weather api to provide weather information of many different cities.
Repository link: https://github.com/keshavjain235/Weather-App
> Weather Android App

- Coding/Python/selection_sort.py
Code in Python to sort a list of integers, using selection sort.
Relevant issue #119
> Selection Sort in Python

- Coding/Python/MaxPriorityQueue.py
> Added Maximum Priority Queue

- Coding/Java/Nokia Keypad.java
> added java code

- Coding/Python/IP LookUp.py
Get External Ip address and Internal IP address of a host
1. External IP: The Ip which your router uses to connect to public internet.
2. Internal IP: The IP used by your device assigned by the network you are connected to.
*Currently provides IPv4 addresses only*
> Added Issue #123 IP LookUp

- Coding/Python/DiamondShapedPatternusingstars.py
- Coding/Python/PalindromeNumber.py
- Coding/Python/SimpleCalculator.py
- ReverseNumber
> Python Simple Calculator

- Coding/Python/tic_tac_toe.py
> Added tic_tac_toe.py

- Coding/Java/Right view of binary tree.java
> Create Right view of binary tree.java

- Coding/C/Emirp Number.c
> Emirp Number

- Coding/Java/Group Anagrams.java
Added Java code of Group Anagrams inside java folder.
> Group Anagrams

- Coding/Java/Largest subarray with 0 sum.java
> Create Largest subarray with 0 sum.java

- Coding/C++/knapsack_problem.cpp
> knapsack_problem

- Coding/C/sedgewick_sort.c
> QuickSort_using_Sedgewick_Sort

- Mobile Development/BirthdayGreet.md
A simple Android App created in Android Studio using Kotlin Language.
> Created BirthdayGreet.md

- Mobile Development/Flutter-Calculator.md
HACTOBERFEST2020 CONTRIBUTION.
> Created Flutter-Calculator.md inside MOBILE DEVELOPMENT.

- Mobile Development/Mimema.md
Mimema is a meme app which shows you random meme from reddit.
> Created Mimema.md File

- Coding/Java/palindromePermutation .java
- Coding/Java/palindromePermutation.java
> Palindrome Permutation solution added

- Cryptography/ECC.java
ECC is one of the widely used cryptographic algorithm. It's a Asymmetric Cryptographic ALgorithm.
> ECC implemented in JAVA

- Coding/Java/paranthesis.java
Added code for 'Check for balanced parentheses in a String' #227
https://github.com/DSC-ChitkaraUniv/HacktoberFest-2020/pull/241/commits/75c101f7ca573b6bc17cbd008175fd143a622268
> Hey I have added java program for Balanced Paranthesis problem

- Coding/Java/bufferreader.java
All possible uses of buffer reader
> bufferreader
